services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf
    secrets:
      - mysql_password

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3305:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    secrets:
      - mysql_password

  rabbitmq:
      image: rabbitmq:management
      container_name: rabbitmq-container
      ports:
        - "5671:5672"
        - "15671:15672"
      networks:
        - app-network
      environment:
        RABBITMQ_DEFAULT_USER: naza
        RABBITMQ_DEFAULT_PASS: uasakso
      healthcheck:
        test: ["CMD", "rabbitmqctl", "status"]
        interval: 30s
        retries: 3
        start_period: 10s
        timeout: 10s

 
volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge

configs:
  nginx_config:
    file: ./nginx.conf

secrets:
  mysql_password:
    file: ./secrets/mysql_password.txt